name: Java Cucumber TestNG Execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment to run tests"  # Input description
        required: true
        default: "Dev"
        options:
          - Dev
          - QA
          - Staging
          - Production
      browser:
        description: "Browser to execute the tests on"  # Input description
        required: true
        default: "chrome"
        options:
          - chrome
          - firefox
          - edge

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome (if browser is Chrome)
        if: ${{ github.event.inputs.browser == 'chrome' }}
        run: sudo apt-get update && sudo apt-get install -y chromium-chromedriver

      - name: Install Firefox (if browser is Firefox)
        if: ${{ github.event.inputs.browser == 'firefox' }}
        run: sudo apt-get update && sudo apt-get install -y firefox-geckodriver

      - name: Install Edge (if browser is Edge)
        if: ${{ github.event.inputs.browser == 'edge' }}
        run: |
          sudo apt-get update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Install Maven Dependencies
        run: mvn install

      - name: Execute Tests
        env:
          TEST_ENV: ${{ github.event.inputs.environment }}
        run: |
          export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
          mvn clean test \
            -Dtest.environment=${{ env.TEST_ENV }} \
            -Dbrowser=${{ github.event.inputs.browser }} \
            -Dwebdriver.chrome.driver=/usr/bin/chromedriver \
            -DchromeOptions.args="--no-sandbox --disable-dev-shm-usage --user-data-dir=${{ runner.temp }}/chrome-session"

      - name: Cleanup Chrome Processes
        run: |
          killall -9 chrome || true
          killall -9 chromedriver || true
