name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    tags: [ "!**" ]  # Run on all pushes except tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven Dependencies
        run: mvn install  # Install dependencies before building

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests with Debugging
        run: |
          export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m -X"
          mvn clean test

  # Additional job for testing with a specific environment (optional)
  test-chrome:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: "Dev"  # Set env variable with static value
    if: ${{ github.event.name == 'push' && github.ref == 'refs/heads/main' &&  github.event.repository.tags.*.name == 'v*' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y chromium-chromedriver
      - name: Run Tests with Chrome
        run: mvn test -Dtest.environment=${{ env.TEST_ENV }} -Dbrowser=chrome
