name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests in'
        required: true
        type: choice
        options:
          - 'dev'
          - 'staging'
          - 'prod'
      browser:
        description: 'Browser to run tests on'
        required: true
        type: choice
        options:
          - 'chrome'
          - 'firefox'
          - 'edge'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23' 
        distribution: 'temurin'
        cache: maven
    - name: Install Browser Drivers
      run: |
        if [[ ${{ inputs.browser }} == 'chrome' ]]; then
          sudo apt-get update && sudo apt-get install -y chromium-chromedriver
        elif [[ ${{ inputs.browser }} == 'firefox' ]]; then
          sudo apt-get update && sudo apt-get install -y firefox geckodriver
        elif [[ ${{ inputs.browser }} == 'edge' ]]; then
          # Install Edge and its driver (instructions may vary depending on your distribution)
          # ...
        fi
    - name: Build and Test
      run: |
        mvn clean test \
          -Dtest.environment=${{ env.TEST_ENV }} \
          -Dbrowser=${{ inputs.browser }}
