name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test (e.g., Dev, Staging, Prod)'
        required: true
        default: 'Dev'
      tag:
        description: 'Test tag to execute (e.g., regression, smoke)'
        required: true
        default: 'regression'
      browser:
        description: 'Browser for test execution (e.g., chrome, firefox)'
        required: true
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y chromium-chromedriver

      - name: Run Tests
        env:
          TEST_ENV: ${{ inputs.environment }}
          TEST_TAG: ${{ inputs.tag }}
          TEST_BROWSER: ${{ inputs.browser }}
        run: |
          echo "Executing tests with:"
          echo "Environment: $TEST_ENV"
          echo "Tag: $TEST_TAG"
          echo "Browser: $TEST_BROWSER"
          mvn test -Dtest.environment=$TEST_ENV -Dtest.tag=$TEST_TAG -Dbrowser=$TEST_BROWSER