name: Selenium Java Automation

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      browser:
        description: 'Browser to run tests on (e.g., chrome, firefox)'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
      tag:
        description: 'Tag to filter tests (e.g., smoke, regression)'
        required: true
        default: 'smoke'
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Set up ChromeDriver (if browser is chrome)
        if: ${{ inputs.browser == 'chrome' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Set up GeckoDriver (if browser is firefox)
        if: ${{ inputs.browser == 'firefox' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-geckodriver

      - name: Run Selenium Tests
        env:
          ENV: ${{ inputs.env }}
          BROWSER: ${{ inputs.browser }}
          TAG: ${{ inputs.tag }}
        run: |
          mvn clean test -Denv=$ENV -Dbrowser=$BROWSER -Dcucumber.filter.tags="@$TAG"
