name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    tags: [ "!**" ]  # Run on all pushes except tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven Dependencies
        run: mvn install  # Install dependencies before building

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests with Debugging
        env:
          TMP_DIR: ${{ runner.temp }}
        run: |
          export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
          mvn clean test \
            -Dwebdriver.chrome.driver=/usr/bin/chromedriver \
            -DchromeOptions.args="--no-sandbox --disable-dev-shm-usage --user-data-dir=${TMP_DIR}/chrome-session"

      - name: Cleanup Chrome Processes
        run: |
          killall -9 chrome || true
          killall -9 chromedriver || true

  test-chrome:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: "Dev"  # Set env variable with static value
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y chromium-chromedriver

      - name: Run Tests with Chrome
        env:
          TMP_DIR: ${{ runner.temp }}
        run: |
          export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
          mvn clean test \
            -Dtest.environment=${{ env.TEST_ENV }} \
            -Dbrowser=chrome \
            -Dwebdriver.chrome.driver=/usr/bin/chromedriver \
            -DchromeOptions.args="--no-sandbox --disable-dev-shm-usage --user-data-dir=${TMP_DIR}/chrome-session"

      - name: Cleanup Chrome Processes
        run: |
          killall -9 chrome || true
          killall -9 chromedriver || true
